name: m6_sudoku
description: A production-ready Flutter Sudoku application built with Clean Architecture, Feature-first architecture, Riverpod, and GoRouter.
version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection: ^1.18.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  custom_lint: ^0.6.0
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.0
  
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/puzzles/

flutter_intl:
  enabled: true
